### ISSUE TITLE
Add Issues Templates

### ISSUE THREAD

**Issue by devarshishimpi** [devarshishimpi/stonecss#42]

**Comment by MrKrishnaAgarwal** [comment]
Hey,
I can work on this issue @devarshishimpi

**Comment by devarshishimpi** [comment]
> Hey, I can work on this issue @devarshishimpi

Hi sure

**Comment by devarshishimpi** [comment]
Issues include

1. Bug Issues
2. Feature Request
3. Contact Support

**Comment by MrKrishnaAgarwal** [comment]
Bug Issues
Feature Request 
**are already added**

**Comment by devarshishimpi** [comment]
> Bug Issues Feature Request **are already added**

Yes, Could you design them as a form fillup style?

**Comment by MrKrishnaAgarwal** [comment]
> > Bug Issues Feature Request **are already added**
> 
> Yes, Could you design them as a form fillup style?

Umm, but they are intended to be like this - it's by github in default

**Comment by devarshishimpi** [comment]
> > > Bug Issues Feature Request **are already added**
> > 
> > 
> > Yes, Could you design them as a form fillup style?
> 
> Umm, but they are intended to be like this - it's by github in default

Yes, like the same thing that Github Is showing, but the fields are separated in the form of blocks. Similar Pattern of when you join a community but for the above required templates.

**Comment by devarshishimpi** [comment]
@MrKrishnaAgarwal  Could you complete this today?

**Comment by MrKrishnaAgarwal** [comment]
> @MrKrishnaAgarwal  Could you complete this today?

Yes, I'll do it asap today itself
