### ISSUE TITLE
To make improvement in footer NavLink Alignment

### ISSUE THREAD

**Issue by psantosh16** [devarshishimpi/stonecss#57]
Problem : - 
Footer Links are not well Aligned in Tablet Mode which is not good for  User Experience (UX) .

Solution:-
Changing some media queries and other things can help with that surely.

**Comment by psantosh16** [comment]
Can I work on this issue ? @devarshishimpi

**Comment by devarshishimpi** [comment]
Thanks For Pointing Out!! Yes sure

**Comment by psantosh16** [comment]
> Thanks For Pointing Out!! Yes sure

Hey , 
I found out one more issue.

Description:-

At Laptop of 1024px , there is blank black gap as shown as below . So , I will resolve this also .
![Screenshot 2022-10-11 at 5 13 32 PM](https://user-images.githubusercontent.com/99491679/195081353-bc9d2d88-2dbe-449e-a632-fa5f23f568f3.png)

**Comment by devarshishimpi** [comment]
> > Thanks For Pointing Out!! Yes sure
> 
> Hey , I found out one more issue.
> 
> Description:-
> 
> At Laptop of 1024px , there is blank black gap as shown as below . So , I will resolve this also . ![Screenshot 2022-10-11 at 5 13 32 PM](https://user-images.githubusercontent.com/99491679/195081353-bc9d2d88-2dbe-449e-a632-fa5f23f568f3.png)

Sure.

**Comment by psantosh16** [comment]
Issue has been resolved from my site . Please , take a look at it . Make MR/PR for same . 
Thank you to letting me contribute to this repo.

**Comment by devarshishimpi** [comment]
Fixed
