### ISSUE TITLE
Blog Post Images are not rendered properly 

### ISSUE THREAD

**Issue by PrakashGatiyala** [devarshishimpi/stonecss#61]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/195897769-d7f694be-defc-4e35-bf3c-24e9708535a6.png)
Hi, As you can see in above Screenshot https://blog.stonecss.com/ blogPost Page images are not rendered properly. 
I want to render the blog Post Images correctly.  
Can I work on this Issue?

**Comment by PrakashGatiyala** [comment]
Hi @devarshishimpi  Can you assign me this issue?

**Comment by devarshishimpi** [comment]
@PrakashGatiyala I have used Ghost Blog for creating the blog. It's not made using own code. ( stonecss.com is made using custom code, this repo contains it as of now ). So changing the code won't be possible, one way for a fix is by changing the image size which fits the size on the blog. And then, I'll have to upload the images to my blog to get it running. Are you fine with it?

**Comment by PrakashGatiyala** [comment]
> @PrakashGatiyala I have used Ghost Blog for creating the blog. It's not made using own code. ( stonecss.com ) is made using custom code, this repo contains it as of now ). So changing the code won't be possible, one way for a fix is by changing the image size which fits the size on the blog. And then, I'll have to upload the images to my blog to get it running. Are you fine with it?

Okay, I will send you resized images. Should I merged them into Images Folder or stonecss/assets/ folder ?

**Comment by devarshishimpi** [comment]
> > @PrakashGatiyala I have used Ghost Blog for creating the blog. It's not made using own code. ( stonecss.com ) is made using custom code, this repo contains it as of now ). So changing the code won't be possible, one way for a fix is by changing the image size which fits the size on the blog. And then, I'll have to upload the images to my blog to get it running. Are you fine with it?
> 
> Okay, I will send you resized images. Should I merged them into Images Folder or stonecss/assets/ folder ?

You can create a temporary folder for it. I will merge it. Then, will add those images to the blog and then delete the folder from here.

**Comment by PrakashGatiyala** [comment]
> > > @PrakashGatiyala I have used Ghost Blog for creating the blog. It's not made using own code. ( stonecss.com ) is made using custom code, this repo contains it as of now ). So changing the code won't be possible, one way for a fix is by changing the image size which fits the size on the blog. And then, I'll have to upload the images to my blog to get it running. Are you fine with it?
> > 
> > 
> > Okay, I will send you resized images. Should I merged them into Images Folder or stonecss/assets/ folder ?
> 
> You can create a temporary folder for it. I will merge it. Then, will add those images to the blog and then delete the folder from here.

Okay.

**Comment by PrakashGatiyala** [comment]
Hi @devarshishimpi I've created the PR. PR link https://github.com/devarshishimpi/stonecss/pull/62
Please review.

**Comment by devarshishimpi** [comment]
Yes, done. Merged
