### ISSUE TITLE
privacypolicy docs do not have clickable website and email link 

### ISSUE THREAD

**Issue by PrakashGatiyala** [devarshishimpi/stonecss#63]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/195993924-dd62dbd4-62e6-4ecf-b219-ec2ca333de4e.png)

Hi @devarshishimpi , In https://stonecss.com/privacypolicy.html document, I have found out that It doesn't have clickable website link and email link(By clicking on email, It should open email app).  
I want to fix this.  Can you assign me ?

**Comment by devarshishimpi** [comment]
Yes sure

**Comment by PrakashGatiyala** [comment]
Hi @devarshishimpi I've created the PR for it. PR link: https://github.com/devarshishimpi/stonecss/pull/64
Kindly review and merge it

**Comment by devarshishimpi** [comment]
Merged. You may want to contribute to https://github.com/dvstechlabs/Noteslify
