### ISSUE TITLE
Placeholder value need update 

### ISSUE THREAD

**Issue by PrakashGatiyala** [devarshishimpi/stonecss#66]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/197338702-07ea7584-9478-451a-8612-2daeb036c923.png)

At contact Page,  https://stonecss.com/contact.html, The message box have wrong placeholder value. 

I want to make it as "Type message here..." 

Hi @devarshishimpi  I want to work on this issue. Can you assign it to me?

**Comment by devarshishimpi** [comment]
Sure

**Comment by PrakashGatiyala** [comment]
> Sure

Hi @devarshishimpi , I have created PR for it. PR link: https://github.com/devarshishimpi/stonecss/pull/67
Kindly review it and merge it.

**Comment by devarshishimpi** [comment]
Done
