### ISSUE TITLE
Website and email link is not clickable in  TERMS OF USE Page.

### ISSUE THREAD

**Issue by PrakashGatiyala** [devarshishimpi/stonecss#68]
### What would you like to share?

![image](https://user-images.githubusercontent.com/34413515/197820063-4405858b-e72f-4dc0-9d85-ff1550e12fac.png)
![image](https://user-images.githubusercontent.com/34413515/197820287-06738c96-7bee-437b-97c8-a1656337f834.png)
![image](https://user-images.githubusercontent.com/34413515/197820613-93cf7fbf-5a1c-4a2d-9075-abfc06fa8f1c.png)

Hi, As you can see, some website link are not clickable in https://stonecss.com/terms.html Page.
I want to make them clickable. 
For Email, I want to make clickable so that It will open email app. 

Hi @devarshishimpi I want to work on this issue. Please assign it to me.

**Comment by devarshishimpi** [comment]
Sure

**Comment by devarshishimpi** [comment]
Done
