### ISSUE TITLE
Other <Contact page clickable email issue>

### ISSUE THREAD

**Issue by lognoroy** [devarshishimpi/stonecss#70]
### What would you like to share?

![Screenshot (3)](https://user-images.githubusercontent.com/87095935/197855401-50ebf50d-0116-45ab-95a8-69f00e579318.png)

I found an issue in this website's Contact page, I want to make these emails clickable.(When user will click it will  open email.)
Hi, @devarshishimpi I want work on this issue, Please assign it to me.

**Comment by lognoroy** [comment]
Hi @devarshishimpi I have created a PR, and my PR link is : https://github.com/devarshishimpi/stonecss/pull/71
Please review it and merge it.

**Comment by devarshishimpi** [comment]
Done
