### ISSUE TITLE
💡 [REQUEST] - Contact Form

### ISSUE THREAD

**Issue by Ayushhgupta39** [devarshishimpi/stonecss#72]
### Start Date

10/27/2022

### Summary

I'd Like to Add a New much better looking contact form to the website. It will enhance the website design experience. Please assign me this enhancement.

### Basic Example

After the New form, the page design will look a lot better.

### Drawbacks

None

**Comment by devarshishimpi** [comment]
@Ayushhgupta39 Could you share an example of the same?
Also, you may want to checkout https://github.com/dvstechlabs/Noteslify 😄

**Comment by Ayushhgupta39** [comment]
Sure!
This is how the contact form will look: 
<img width="284" alt="image" src="https://user-images.githubusercontent.com/96309609/198210885-5ad3f58a-154f-4ce4-ad7f-4107ea7435ff.png">

**Comment by devarshishimpi** [comment]
> Sure! This is how the contact form will look: <img alt="image" width="284" src="https://user-images.githubusercontent.com/96309609/198210885-5ad3f58a-154f-4ce4-ad7f-4107ea7435ff.png">

Great!! Build with the same colour theme and being responsive

**Comment by Ayushhgupta39** [comment]
Okay!

**Comment by devarshishimpi** [comment]
This won't be worked on
