### ISSUE TITLE
💡 [REQUEST] - I would like to add a move to top page button.

### ISSUE THREAD

**Issue by abhay-raj19** [devarshishimpi/stonecss#76]
### Start Date

OCT/29/2k22

### Summary

I want to add a move to top page button in the bottom right corner of the page.

which would somewhat look like this .

<img width="76" alt="image" src="https://user-images.githubusercontent.com/96302417/198828655-44fd8929-ee45-4f90-b95c-2a2b207d609e.png">

***✨FEATURES OF THE BUTTON✨***

>👉Hovering effect on cursor on it.
>👉Will zoom little bit so that user can confirm .
>👉Will take you to the top of the page on clicking on it.

Pls assign me (@devarshishimpi ) , I will make the best suggested changes.

### Basic Example

<img width="976" alt="image" src="https://user-images.githubusercontent.com/96302417/198829224-d49f26e5-b172-41eb-9d50-868708ec80e5.png">

### Drawbacks

N/A

**Comment by devarshishimpi** [comment]
Sure

**Comment by supsa-ak** [comment]
Hi, assign this to me

**Comment by abhay-raj19** [comment]
✅I had done the suggested changes and raised a pull request #77 .

Pls do see it.

**Comment by devarshishimpi** [comment]
Fixed
